---
- name: Deploy KVM Host on AWS
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars/main.yml

  tasks:
    - name: Set AWS region for tasks
      set_fact:
        aws_region: "{{ aws_region }}"

    - name: Create a VPC
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ aws_region }}"
        tags:
          Name: "{{ vpc_name }}"
      register: vpc

    - name: Get availability zones for region
      amazon.aws.aws_az_info:
        region: "{{ aws_region }}"
      register: azs

    - name: Create subnets
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ aws_region }}"
        az: "{{ item.zone_name }}"
        map_public: yes
        cidr: "{{ vpc_cidr | ansible.utils.ipaddr(24, index+10) }}"
        tags:
          Name: "{{ subnet_name }}-{{ item.zone_name }}"
      loop: "{{ azs.availability_zones }}"
      loop_control:
        index_var: index
      register: subnets

    - name: Create an Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ aws_region }}"
        tags:
          Name: "{{ igw_name }}"
      register: igw

    - name: Create a route table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ aws_region }}"
        subnets: "{{ subnets.results | map(attribute='subnet.id') | list }}"
        routes:
          - dest: "0.0.0.0/0"
            gateway_id: "{{ igw.gateway_id }}"
        tags:
          Name: "{{ route_table_name }}"

    - name: Create Security Group
      amazon.aws.ec2_group:
        name: "{{ instance_name }}-sg"
        description: "Security group for KVM Host"
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: "0.0.0.0/0"
            rule_desc: "Allow SSH from anywhere"
          - proto: all
            group_name: "{{ instance_name }}-sg"
            rule_desc: "Allow all traffic within the security group"
      register: sg

    # - name: Generate list of private IPs for ENI
    #   set_fact:
    #     private_ips: "{{ [host_ip] + range(kvm_ip_range.start, kvm_ip_range.end + 1) | map('regex_replace', '^(.*)$', kvm_ip_range.prefix + '.\\1') | list }}"


    - name: Generate block device mappings
      set_fact:
        block_device_mappings: |
          {% set mappings = [] %}
          {% set root_disk = {'device_name': '/dev/sda1', 'ebs': {'volume_size': disk_config.root_disk_size_gb | default(60), 'volume_type': 'gp3', 'iops': 3000, 'delete_on_termination': true}} %}
          {% set _ = mappings.append(root_disk) %}
          {% set first_disk = {'device_name': '/dev/sdb', 'ebs': {'volume_size': 2, 'volume_type': 'gp3', 'iops': 3000, 'delete_on_termination': true}} %}
          {% set _ = mappings.append(first_disk) %}
          {% if disk_config.num_data_disks > 0 %}
          {%   set individual_disk_size_gb = (disk_config.total_data_size_gb / disk_config.num_data_disks) | int %}
          {%   set device_letters = 'cdefghijklmnopqrstuvwxyz' %}
          {%   for i in range(disk_config.num_data_disks) %}
          {%     set device_name = '/dev/sd' + device_letters[i] %}
          {%     set data_disk = {'device_name': device_name, 'ebs': {'volume_size': individual_disk_size_gb, 'volume_type': 'gp3', 'iops': 3000, 'delete_on_termination': true}} %}
          {%     set _ = mappings.append(data_disk) %}
          {%   endfor %}
          {% endif %}
          {{ mappings | to_json }}

    - name: Find availability zones that support the instance type
      amazon.aws.aws_az_info:
        region: "{{ aws_region }}"
        filters:
          instance-type:
            - "{{ instance_type }}"
      register: instance_type_info

    - name: Extract the available zones
      set_fact:
        available_zones_for_instance_type: "{{ instance_type_info.instance_types[instance_type].usages | map(attribute='availability_zone') | list }}"

    - name: Find a suitable subnet in an available zone
      set_fact:
        target_subnet_id: "{{ (subnets.results | selectattr('item.zone_name', 'in', available_zones_for_instance_type) | list | first).subnet.id }}"

    - name: Launch the c5n.metal instance
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        subnet_id: "{{ target_subnet_id }}"
        security_groups:
          - "{{ sg.group_id }}"
        source_dest_check: no
        assign_public_ip: yes
        volumes: "{{ block_device_mappings | from_json }}"
        region: "{{ aws_region }}"
        wait: yes
      register: ec2

    - name: Print instance details
      debug:
        msg: "Instance {{ ec2.instance_ids[0] }} is running at {{ ec2.instances[0].public_ip_address }}"
